import type { Cotizacion } from './store/cotizaciones-store'

export const demoCotizaciones: Cotizacion[] = [
  {"id": "cot-01", "nro_cotizacion": "COT-0001", "fecha": "2026-08-02", "cliente_id": "cli-03", "propiedad_id": "demo-01", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 625600000, "condiciones_pago": "30% inicial, saldo a 30 días", "observaciones": "Cotización para Edificio Bahía Poblado — Andrés Ríos", "situacion": "En Negociación"},
  {"id": "cot-02", "nro_cotizacion": "COT-0002", "fecha": "2026-08-03", "cliente_id": "cli-05", "propiedad_id": "demo-02", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 1125000000, "condiciones_pago": "Crédito hipotecario", "observaciones": "Cotización para Finca La Esperanza — Juan Ospina", "situacion": "Aceptada"},
  {"id": "cot-03", "nro_cotizacion": "COT-0003", "fecha": "2026-08-04", "cliente_id": "cli-07", "propiedad_id": "demo-03", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 846400000, "condiciones_pago": "Crédito hipotecario", "observaciones": "Cotización para Casa Alto de las Palmas — Diego Salazar", "situacion": "Rechazada"},
  {"id": "cot-04", "nro_cotizacion": "COT-0004", "fecha": "2026-08-05", "cliente_id": "cli-09", "propiedad_id": "demo-04", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 66000000, "condiciones_pago": "30% inicial, saldo a 30 días", "observaciones": "Cotización para Torre Parque 93 — Santiago Rodríguez", "situacion": "Enviada"},
  {"id": "cot-05", "nro_cotizacion": "COT-0005", "fecha": "2026-08-06", "cliente_id": "cli-11", "propiedad_id": "demo-05", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 540000000, "condiciones_pago": "Crédito hipotecario", "observaciones": "Cotización para Local Comercial Laureles — Felipe Castro", "situacion": "En Negociación"},
  {"id": "cot-06", "nro_cotizacion": "COT-0006", "fecha": "2026-08-07", "cliente_id": "cli-13", "propiedad_id": "demo-06", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 39900000, "condiciones_pago": "50% reserva, 50% escritura", "observaciones": "Cotización para Finca Villa Marta — Sebastián Restrepo", "situacion": "Aceptada"},
  {"id": "cot-07", "nro_cotizacion": "COT-0007", "fecha": "2026-08-08", "cliente_id": "cli-15", "propiedad_id": "demo-07", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 395600000, "condiciones_pago": "Contado", "observaciones": "Cotización para Conjunto Ciudad Jardín — Mateo Mejía", "situacion": "Rechazada"},
  {"id": "cot-08", "nro_cotizacion": "COT-0008", "fecha": "2026-08-09", "cliente_id": "cli-02", "propiedad_id": "demo-08", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 1567500000, "condiciones_pago": "50% reserva, 50% escritura", "observaciones": "Cotización para Casa Campestre Llanogrande — María Muñoz", "situacion": "Enviada"},
  {"id": "cot-09", "nro_cotizacion": "COT-0009", "fecha": "2026-08-10", "cliente_id": "cli-04", "propiedad_id": "demo-09", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 93600000, "condiciones_pago": "50% reserva, 50% escritura", "observaciones": "Cotización para Centro Empresarial Santa Bárbara — Laura Moreno", "situacion": "En Negociación"},
  {"id": "cot-10", "nro_cotizacion": "COT-0010", "fecha": "2026-08-11", "cliente_id": "cli-06", "propiedad_id": "demo-10", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 245000000, "condiciones_pago": "30% inicial, saldo a 30 días", "observaciones": "Cotización para Apartaestudio Sabaneta Park — Sofía Quintero", "situacion": "Aceptada"},
  {"id": "cot-11", "nro_cotizacion": "COT-0011", "fecha": "2026-08-12", "cliente_id": "cli-08", "propiedad_id": "demo-01", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 680000000, "condiciones_pago": "30% inicial, saldo a 30 días", "observaciones": "Cotización para Edificio Bahía Poblado — Valentina Villa", "situacion": "Rechazada"},
  {"id": "cot-12", "nro_cotizacion": "COT-0012", "fecha": "2026-08-13", "cliente_id": "cli-10", "propiedad_id": "demo-02", "comercial_id": "", "tipo_moneda": "COP", "precio_ofertado": 1250000000, "condiciones_pago": "Contado", "observaciones": "Cotización para Finca La Esperanza — Camila García", "situacion": "Enviada"},
]
