import type { Solicitud } from './store/solicitudes-store'

export const demoSolicitudes: Solicitud[] = [
  {"id": "sol-01", "codigo": "SOL-0001", "fecha": "2026-08-04", "nombre": "Juan", "apellido": "García", "correo": "juan1@correo.com", "telefono": "324 387 1064", "mensaje": "Estoy interesado en Casa Alto de las Palmas, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-03", "estado": "Nueva", "comercial_asignado": "", "notas": ""},
  {"id": "sol-02", "codigo": "SOL-0002", "fecha": "2026-08-07", "nombre": "Santiago", "apellido": "Herrera", "correo": "santiago2@correo.com", "telefono": "314 376 3319", "mensaje": "Estoy interesado en Local Comercial Laureles, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-05", "estado": "En Atencion", "comercial_asignado": "", "notas": ""},
  {"id": "sol-03", "codigo": "SOL-0003", "fecha": "2026-08-10", "nombre": "Sebastián", "apellido": "Ospina", "correo": "sebastián3@correo.com", "telefono": "325 833 2971", "mensaje": "Estoy interesado en Conjunto Ciudad Jardín, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-07", "estado": "Atendida", "comercial_asignado": "", "notas": ""},
  {"id": "sol-04", "codigo": "SOL-0004", "fecha": "2026-08-13", "nombre": "Nicolás", "apellido": "Mejía", "correo": "nicolás4@correo.com", "telefono": "327 263 6340", "mensaje": "Estoy interesado en Centro Empresarial Santa Bárbara, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-09", "estado": "Nueva", "comercial_asignado": "", "notas": ""},
  {"id": "sol-05", "codigo": "SOL-0005", "fecha": "2026-08-16", "nombre": "David", "apellido": "Ramírez", "correo": "david5@correo.com", "telefono": "326 743 8905", "mensaje": "Estoy interesado en Edificio Bahía Poblado, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-01", "estado": "En Atencion", "comercial_asignado": "", "notas": ""},
  {"id": "sol-06", "codigo": "SOL-0006", "fecha": "2026-08-19", "nombre": "Samuel", "apellido": "García", "correo": "samuel6@correo.com", "telefono": "313 773 1930", "mensaje": "Estoy interesado en Casa Alto de las Palmas, ¿podrían darme más información y agendar una visita?", "origen": "Portal Web", "propiedad_id": "demo-03", "estado": "Atendida", "comercial_asignado": "", "notas": ""},
]
